spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/vhrsystem?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: '010220'
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.Springdemo.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  flie:
    path: G:\IdeaProjects\Springdemo\
server:
  port: 8989
    #ssl:
    #key-store: classpath:pe.cnxfs.com.cn.jks
    #key-password: 3ut56oahv0y
  #key-store-type: JKS
